### ISSUE TITLE
Add "City" Field

### ISSUE THREAD

**Issue by TheArchitect4855** [wilrnh/emergencywalletcards.com#31]
I'm guessing this is supposed to go in address line 1, but it would be more clear if there was a separate City field.

**Comment by kwhitefoot** [comment]
Please do not use a multitude of fields for the address.  It should be a free text field because there are many variations on how an address is presented.  Some people live in villages that have no street names, some have no postcodes, some have no house numbers, some national standards and traditional ways of writing addresses differ from others, etc.

See also: https://www.mjt.me.uk/posts/falsehoods-programmers-believe-about-addresses/

**Comment by TheArchitect4855** [comment]
Damn, I didn't think of that - Good point.
